### ISSUE TITLE
useAppOpenAd still shows after disabling it

### ISSUE THREAD

**Issue by andkom** [react-native-admob/admob#33]
I have paid option to disable ads:

```
useAppOpenAd(initialized && !disableAds ? unitId : null, {
  showOnColdStart: false,
  showOnAppForeground: true,
});
```

but after an user purchases ads removal, app open ad still shows on app foreground

**Comment by nguyen95** [comment]
I used AppOpenAd component and it work. In your case, I think init method not called again
Doc: https://react-native-admob.github.io/admob/docs/api/AppOpenAd

**Comment by andkom** [comment]
the issue is: once AppOpenAd has been initialized, there is no way do disable it runtime. Only restart the app.

**Comment by nguyen95** [comment]
Please read the doc. 
Call AppOpenAd.createAd('', {
  showOnColdStart: false,
  showOnAppForeground: false,
})
again to disable

**Comment by nguyen95** [comment]
Note that the unitId in second must be different in first, if not, the init() method in native code will not call again

**Comment by wjaykim** [comment]
@nguyen95 Yes, that is one way to disable it, but it is not hookish way. I'll improve the code to disable just by setting unitId undefined.

**Comment by andkom** [comment]
@nguyen95 yeah, but it looks like a hack

**Comment by wjaykim** [comment]
Fixed in 1.2.0

**Comment by andkom** [comment]
@wjaykim bug is not fixed

```
<AppOpenAdProvider
      unitId={isPaid ? null : TestIds.APP_OPEN}
      options={{ showOnColdStart: true, showOnForeground: true }}
    >
      {/* ... */}
</AppOpenAdProvider>
```

if `isPaid` changes to true, ad still shows on app foreground

**Comment by wjaykim** [comment]
@andkom oh, thank you for reporting. This issue had been fixed, but it has been occurring again since several updates. I'll fix this issue again.

**Comment by wjaykim** [comment]
Fixed in 1.4.0

**Comment by andkom** [comment]
as for now `showOnAppForeground` behavior is not consistent, sometimes it works, sometimes not, but disabling AppOpenAd in runtime is still not working

**Comment by wjaykim** [comment]
I've tested and it's working you have to reproduce your code so that I can help you.
